module.exports = {
    "rules": {
        "array-bracket-spacing": [2, "never"],
        "accessor-pairs": 0,
        "block-scoped-var": 2,
        "block-spacing": [2, "always"],
        "brace-style": [2, "1tbs"],
        "camelcase": 2,
        "comma-dangle": [2, "never"],
        "comma-spacing": 2,
        "comma-style": 2,
        "complexity": [2, 4],
        "computed-property-spacing": [2, "never"],
        "consistent-return": 2,
        "consistent-this": [2, "self"],
        "curly": [2, "all"],
        "default-case": 2,
        "dot-location": [2, "property"],
        "dot-notation": [2, {"allowKeywords": true}],
        "eol-last": 2,
        "eqeqeq": 2,
        "func-names": 0,
        "func-style": [0, "declaration"],
        "guard-for-in": 2,
        "id-length": 0,
        "indent": [2, 4],
        "init-declarations": 0,
        "jsx-quotes": [2, "prefer-single"],
        "key-spacing": [2, {"beforeColon": false, "afterColon": true}],
        "linebreak-style": [2, "unix"],
        "lines-around-comment": 0,
        "max-depth": [2, 2],
        "max-len": [0, 80, 4],
        "max-nested-callbacks": [0, 2],
        "max-params": [0, 3],
        "max-statements": [2, 10],
        "new-cap": 0,
        "new-parens": 2,
        "newline-after-var": 2,
        "no-alert": 2,
        "no-array-constructor": 2,
        "no-bitwise": 2,
        "no-caller": 2,
        "no-case-declarations": 2,
        "no-catch-shadow": 2,
        "no-cond-assign": 2,
        "no-console": 2,
        "no-constant-condition": 2,
        "no-continue": 2,
        "no-control-regex": 2,
        "no-debugger": 2,
        "no-delete-var": 2,
        "no-div-regex": 2,
        "no-dupe-keys": 2,
        "no-dupe-args": 2,
        "no-duplicate-case": 2,
        "no-else-return": 2,
        "no-empty": 2,
        "no-empty-character-class": 2,
        "no-empty-pattern": 2,
        "no-eq-null": 2,
        "no-eval": 2,
        "no-ex-assign": 2,
        "no-extend-native": 2,
        "no-extra-bind": 2,
        "no-extra-boolean-cast": 2,
        "no-extra-parens": 0,
        "no-extra-semi": 2,
        "no-fallthrough": 2,
        "no-floating-decimal": 2,
        "no-func-assign": 2,
        "no-implicit-coercion": 2,
        "no-implied-eval": 2,
        "no-inline-comments": 0,
        "no-inner-declarations": [2, "functions"],
        "no-invalid-regexp": 2,
        "no-invalid-this": 2,
        "no-irregular-whitespace": 2,
        "no-iterator": 2,
        "no-label-var": 2,
        "no-labels": 2,
        "no-lone-blocks": 2,
        "no-lonely-if": 2,
        "no-loop-func": 2,
        "no-mixed-spaces-and-tabs": 2,
        "no-multi-spaces": 2,
        "no-multi-str": 2,
        "no-multiple-empty-lines": [2, {"max": 1}],
        "no-native-reassign": 2,
        "no-negated-condition": 0,
        "no-negated-in-lhs": 2,
        "no-nested-ternary": 2,
        "no-new": 2,
        "no-new-func": 2,
        "no-new-object": 2,
        "no-new-wrappers": 2,
        "no-obj-calls": 2,
        "no-octal": 2,
        "no-octal-escape": 2,
        "no-param-reassign": 2,
        "no-plusplus": [2, {allowForLoopAfterthoughts: true}],
        "no-process-env": 2,
        "no-proto": 2,
        "no-redeclare": 2,
        "no-regex-spaces": 2,
        "no-restricted-syntax": 0,
        "no-return-assign": 2,
        "no-script-url": 2,
        "no-self-compare": 2,
        "no-sequences": 2,
        "no-shadow": 2,
        "no-shadow-restricted-names": 2,
        "no-spaced-func": 2,
        "no-sparse-arrays": 2,
        "no-ternary": 0,
        "no-trailing-spaces": 2,
        "no-throw-literal": 2,
        "no-undef": 2,
        "no-undef-init": 0,
        "no-undefined": 0,
        "no-unexpected-multiline": 2,
        "no-underscore-dangle": 0,
        "no-unneeded-ternary": 2,
        "no-unreachable": 2,
        "no-unused-expressions": [2, {allowTernary: true}],
        "no-unused-vars": [2, {"vars": "all", "args": "after-used"}],
        "no-use-before-define": 2,
        "no-useless-call": 2,
        "no-useless-concat": 2,
        "no-void": 0,
        "no-warning-comments": 0,
        "no-with": 2,
        "no-magic-numbers": [2, {ignore: [-1, 0, 1, 2]}],
        "object-curly-spacing": [2, "never"],
        "one-var": [2, {"var": "always", "let": "always", "const": "never"}],
        "operator-assignment": 0,
        "operator-linebreak": [2, "after"],
        "padded-blocks": [0],
        "quote-props": [2, "as-needed", {"unnecessary": false, "numbers": true}],
        "quotes": [2, "single", "avoid-escape"],
        "radix": [2, "always"],
        "id-match": 0,
        "require-jsdoc": 0,
        "semi": 2,
        "semi-spacing": 2,
        "sort-vars": 0,
        "space-before-blocks": [2, "always"],
        "space-before-function-paren": [2, {"anonymous": "always", "named": "never"}],
        "space-in-parens": [2, "never"],
        "space-infix-ops": 2,
        "space-unary-ops": [2, {"words": true, "nonwords": false}],
        "spaced-comment": 2,
        "strict": 0,
        "use-isnan": 2,
        "valid-jsdoc": 2,
        "valid-typeof": 2,
        "vars-on-top": 2,
        "wrap-iife": [2, "outside"],
        "wrap-regex": 0,
        "yoda": [2, "never"]
    }
};
