export const CALCULATION_LOAD_ERROR = 'CALCULATION_LOAD_ERROR';
export const CALCULATION_LOAD_START = 'CALCULATION_LOAD_START';
export const CALCULATION_LOADED = 'CALCULATION_LOADED';
export const NORMAL_INCOME_CHANGED = 'NORMAL_INCOME_CHANGED';
